### ISSUE TITLE
Add routing

### ISSUE THREAD

**Issue by sarmadH97** [hinchley2018/learning-ecommerce#20]
Add routing to the frontend application

**Comment by Prerak1310** [comment]
is it okay if I had a pages folder within the src and add multiple pages like home page checkout page etc to that folder. Then I can route those?

**Comment by sarmadH97** [comment]
@Prerak1310 You can add two pages for now, the Products page and the Cart page, rename the "view" folder to pages and continue to configure the routing, update the App.js file accordingly.
