### ISSUE TITLE
Build order checkout page

### ISSUE THREAD

**Issue by hinchley2018** [hinchley2018/learning-ecommerce#3]
Displays the products from the users cart

And calculates the order total

When submit order is clicked a loading spinner is displayed 

Meanwhile it makes a request to the backend with the order info

If there is an error it shows it

If order succeeds send the user to the order confirmation screen with the order id

This screenshot shows the idea/inspiration but you don't have to copy exactly 

![image](https://github.com/hinchley2018/learning-ecommerce/assets/17077365/8385706e-6ca3-4a2a-85c3-59f1caade0d5)

**Comment by saandre0217** [comment]
Assigned this to myself, because I would like to have a hand in this, but definitely open to pair programming or sharing responsibilities if anyone else is interesting in working on this as well.
